// <auto-generated />
namespace MyBlog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addSummaryToarticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSummaryToarticle));
        
        string IMigrationMetadata.Id
        {
            get { return "201406270440297_addSummaryToarticle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
